import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { useContext } from 'react';
import { CanUserSee } from '../components/can-user-see';
import { AuthContext, signOut } from '../contexts/auth';
import { withSSRAuth } from '../utils/with-ssr-auth';

const DashboardPage: NextPage = () => {
  const { user } = useContext(AuthContext);

  return (
    <div>
      <Head>
        <title>Dashboard Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Dashboard</h1>

      <h3>Hello mr: {user?.email} </h3>

      <button onClick={signOut}>sign out</button>

      <CanUserSee permissions={['metrics.list']}>
        <h1>user</h1>
      </CanUserSee>
    </div>
  );
};

export default DashboardPage;

export const getServerSideProps: GetServerSideProps = withSSRAuth(
  async (context) => {
    return {
      props: {},
    };
  }
);
