import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { FormEvent, useContext, useState } from 'react';
import { AuthContext } from '../contexts/auth';
import { withSSRQuest } from '../utils/with-ssr-guest';

const Home: NextPage = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const { signIn } = useContext(AuthContext);

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();

    const data = {
      email,
      password,
    };

    signIn(data);
  };

  return (
    <div>
      <Head>
        <title>Next Auth</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <form onSubmit={handleSubmit}>
        <div>
          <label htmlFor='email'>Email address</label>
          <br />
          <input
            type='email'
            name='email'
            id='email'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            title='Type ur email'
          />
        </div>
        <div>
          <label htmlFor='password'>Password</label> <br />
          <input
            type='password'
            name='email'
            id='password'
            value={password}
            onChange={(e) => setPassword(e.target.value)}
            title='Type ur password'
          />
        </div>
        <button type='submit'>Log in</button>
      </form>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = withSSRQuest(async () => {
  return {
    props: {},
  };
});
