import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { withSSRAuth } from '../utils/with-ssr-auth';

const Metrics: NextPage = () => {
 
  return (
    <div>
      <Head>
        <title>Metrics</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

     <h1>Metrics</h1>
    </div>
  );
};

export default Metrics;

export const getServerSideProps: GetServerSideProps = withSSRAuth(async () => {
  return {
    props: {},
  };
}, {
  permissions: ['metrics.list3'],
  roles: ['administrator']
});
